augment: true
augment_times: 2
augment_times_query: 1
backbone:
  kwargs:
    is_flatten: false
    maxpool_last2: false
  name: resnet12
batch_size: 64
classifier:
  kwargs:
    n_k: 3
  name: ADM
data_root: ./WebCaricature

dataloader_num: 1
deterministic: true
device_ids: 0,1
episode_size: 2
epoch: 40
image_size: 84
includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
- classifiers/ADM.yaml
- backbones/Conv64F.yaml
log_interval: 100
log_level: info
log_name: null
log_paramerter: false
lr_scheduler:
  kwargs:
    gamma: 0.1
    milestones:
    - 20
    - 30
  name: MultiStepLR
n_gpu: 2
optimizer:
  kwargs:
    lr: 0.01
    momentum: 0.9
    nesterov: true
    weight_decay: 0.001
  name: SGD
  other: null
parallel_part:
- emb_func
port: 38318
pretrain_path: null
query_num: 10
rank: 0
result_root: ./results
resume: false
save_interval: 50
save_part:
- emb_func
seed: 2147483647
shot_num: 5
tag: null
tb_scale: 1.0
test_episode: 1000
test_epoch: 5
test_query: 10
test_shot: 5
test_way: 5
train_episode: 1000
use_memory: false
val_per_epoch: 1
warmup: 0
way_num: 5
workers: 8
